export const CATEGORIZED_INGREDIENTS = {
  "Manav": [
    "domates",
    "biber",
    "sivri biber",
    "çarliston biber",
    "kırmızı biber",
    "kapya biber",
    "dolmalık biber",
    "patlıcan",
    "kemer patlıcan",
    "bostan patlıcan",
    "kuru soğan",
    "taze soğan",
    "sarımsak",
    "patates",
    "taze patates",
    "kabak",
    "bal kabağı",
    "havuç",
    "ispanak",
    "kereviz",
    "pırasa",
    "karnabahar",
    "brokoli",
    "lahana",
    "kara lahana",
    "brüksel lahanası",
    "enginar",
    "bamya",
    "börülce",
    "taze fasulye",
    "mantar",
    "kültür mantarı",
    "i̇stiridye mantarı",
    "roka",
    "tere",
    "nane",
    "maydanoz",
    "dereotu",
    "kuzu kulağı",
    "marul",
    "kıvırcık",
    "göbek salata",
    "şalgam",
    "turp",
    "kuşkonmaz",
    "elma",
    "armut",
    "ayva",
    "muz",
    "çilek",
    "karpuz",
    "kavun",
    "üzüm",
    "siyah üzüm",
    "i̇ncir",
    "kiraz",
    "vişne",
    "şeftali",
    "kayısı",
    "erik",
    "nar",
    "portakal",
    "mandalina",
    "limon",
    "greyfurt",
    "kivi",
    "avokado",
    "mango",
    "ananas",
    "yaban mersini",
    "böğürtlen",
    "ahududu"
  ],
  "Süt ve Süt Ürünleri": [
    "süt",
    "yoğurt",
    "süzme yoğurt",
    "tereyağı",
    "krema",
    "kaymak",
    "beyaz peynir",
    "süzme peynir",
    "eski kaşar",
    "taze kaşar",
    "ezine peyniri",
    "tulum peyniri",
    "çeçil peyniri",
    "örgü peyniri",
    "burgu peyniri",
    "tel peynir",
    "dil peyniri",
    "hellim",
    "lor peyniri",
    "çökelek",
    "labne",
    "krem peynir",
    "gravyer",
    "cheddar",
    "mozzarella",
    "parmesan",
    "gouda",
    "kefir",
    "ayran"
  ],
  "Et Ürünleri": [
    "kıyma",
    "kuşbaşı",
    "antrikot",
    "bonfile",
    "kontrfile",
    "tranç",
    "nuar",
    "bodigo",
    "gerdan",
    "i̇ncik",
    "kaburga",
    "pirzola",
    "biftek",
    "kavurma",
    "pastırma",
    "kangal sucuk",
    "parmak sucuk",
    "sosis",
    "salam",
    "füme et",
    "jambon",
    "ciğer",
    "yürek",
    "böbrek",
    "i̇şkembe"
  ],
  "Tavuk ve Deniz Ürünleri": [
    "bütün tavuk",
    "tavuk göğsü",
    "tavuk but",
    "tavuk kanat",
    "tavuk i̇ncik",
    "baget",
    "tavuk ciğeri",
    "taşlık",
    "hindi göğüs",
    "bütün hindi",
    "somon",
    "levrek",
    "çipura",
    "hamsi",
    "i̇stavrit",
    "lüfer",
    "palamut",
    "mezgit",
    "uskumru",
    "sardalya",
    "kalkan",
    "barbun",
    "tekir",
    "kefal",
    "karides",
    "kalamar",
    "midye"
  ],
  "Bakliyat ve Temel Gıda": [
    "pirinç",
    "bulgur",
    "kırmızı mercimek",
    "yeşil mercimek",
    "sarı mercimek",
    "kuru fasulye",
    "nohut",
    "barbunya",
    "börülce",
    "bakla",
    "bezelye",
    "mısır",
    "kinoa",
    "yulaf",
    "i̇rmik",
    "arpa şehriye",
    "tel şehriye",
    "tarhana",
    "un",
    "mısır unu",
    "galeta unu",
    "somun ekmek",
    "lavaş",
    "yufka",
    "spagetti",
    "penne",
    "burgu makarna",
    "kelebek makarna",
    "erişte",
    "mantı",
    "şeker",
    "zeytinyağı",
    "ayçiçek yağı",
    "tereyağı",
    "yumurta",
    "domates salçası",
    "biber salçası",
    "sirke",
    "tuz",
    "karabiber",
    "pul biber",
    "kekik",
    "nane",
    "kimyon"
  ]
};
export const INGREDIENT_KEYWORDS = Object.values(CATEGORIZED_INGREDIENTS).flat();
