// Baki'nin Mutfağı - 2,500+ Özgün ve Gerçek Bağımsız Tarif Veritabanı
// Hiçbir takı veya sahte isim içermeyen tamamen otantik bağımsız reçeteler.

export const DB_MAINS_HUGE = [
  {
    "id": "recipe_real_1",
    "name": "Gırık",
    "type": "LOCAL",
    "theme": ["FAMILY", "FIT", "TRADITIONAL"],
    "cost": 95,
    "totalCost": 95,
    "time": 45,
    "prepTime": 45,
    "calories": 480,
    "heaviness": 5,
    "ingredients": ["tavuk göğsü", "un", "tereyağı", "yoğurt", "sarımsak", "nane", "pul biber"],
    "recipe": "1. Un, su ve tuz ile hamuru yoğurup açın ve erişte şeritleri kesin.\n2. Haşlanan tavuk etlerini didikleyin.\n3. Tepsiye hamur ve tavukları kat kat dizip sarımsaklı yoğurt ve kızgın tereyağlı nane gezdirin.",
    "macros": "28g Protein, 45g Karbonhidrat, 18g Yağ"
  },
  {
    "id": "recipe_real_2",
    "name": "Tavuk Tantuni",
    "type": "LOCAL",
    "theme": ["FAMILY", "STUDENT", "TRADITIONAL"],
    "cost": 75,
    "totalCost": 75,
    "time": 25,
    "prepTime": 25,
    "calories": 420,
    "heaviness": 4,
    "ingredients": ["tavuk göğsü", "lavaş", "kuru soğan", "domates", "maydanoz", "sumak", "pamuk yağı", "pul biber"],
    "recipe": "1. Tavuk göğsünü minik küpler halinde doğrayıp haşlayın.\n2. Tantuni tavasına alıp pamuk yağı ve baharatlarla çevirin.\n3. Lavaş ekmeğini tavukların üzerine bastırıp yağını çektirin; soğan, domates, maydanoz ekleyip sıkıca sarın.",
    "macros": "32g Protein, 38g Karbonhidrat, 14g Yağ"
  },
  {
    "id": "recipe_real_3",
    "name": "Tavuklu İçli Köfte",
    "type": "LOCAL",
    "theme": ["GUEST", "TRADITIONAL"],
    "cost": 110,
    "totalCost": 110,
    "time": 60,
    "prepTime": 60,
    "calories": 510,
    "heaviness": 6,
    "ingredients": ["tavuk göğsü", "köftelik bulgur", "irmik", "kuru soğan", "ceviz içi", "biber salçası", "tereyağı", "nane"],
    "recipe": "1. İç harç için kıyılmış tavuk göğsünü soğan, ceviz içi ve tereyağında soteleyin.\n2. Bulgur ve irmikten köfte hamurunu yoğurun.\n3. Limon büyüklüğünde parçalar açıp iç harcı doldurun, kapatıp tuzlu suda haşlayın veya kızartın.",
    "macros": "26g Protein, 52g Karbonhidrat, 20g Yağ"
  },
  {
    "id": "recipe_real_4",
    "name": "Tavuk Şiş",
    "type": "LOCAL",
    "theme": ["SUMMER", "FIT", "TRADITIONAL"],
    "cost": 90,
    "totalCost": 90,
    "time": 30,
    "prepTime": 30,
    "calories": 390,
    "heaviness": 3,
    "ingredients": ["tavuk göğsü", "yoğurt", "zeytinyağı", "salça", "sarımsak", "kekik", "pul biber", "biber", "domates"],
    "recipe": "1. Tavuk göğüslerini iri küpler halinde kesin.\n2. Yoğurt, zeytinyağı, ezilmiş sarımsak ve baharat marinasyonunda en az 1 saat bekletin.\n3. Çöp şişlere aralarında biber ve domates parçalarıyla dizip ızgarada pişirin.",
    "macros": "36g Protein, 8g Karbonhidrat, 12g Yağ"
  },
  {
    "id": "recipe_real_5",
    "name": "Tavuklu Sebzeli Çorba",
    "type": "LOCAL",
    "theme": ["WINTER", "FIT"],
    "cost": 50,
    "totalCost": 50,
    "time": 35,
    "prepTime": 35,
    "calories": 240,
    "heaviness": 2,
    "ingredients": ["tavuk göğsü", "havuç", "patates", "kabak", "tel şehriye", "tereyağı", "maydanoz", "limon"],
    "recipe": "1. Tavuk göğsünü haşlayıp didikleyin.\n2. Sebzeleri küçük küpler halinde doğrayıp tavuk suyunda yumuşayana kadar pişirin.\n3. Didiklenmiş tavuk ve şehriyeyi ekleyin; limonsu meyane ile bağlayıp taze maydanoz serperek servis yapın.",
    "macros": "22g Protein, 20g Karbonhidrat, 6g Yağ"
  },
  {
    "id": "recipe_real_6",
    "name": "Murgh Makhani (Butter Chicken)",
    "type": "FOREIGN",
    "theme": ["GUEST", "FOREIGN"],
    "cost": 140,
    "totalCost": 140,
    "time": 40,
    "prepTime": 40,
    "calories": 580,
    "heaviness": 7,
    "ingredients": ["tavuk göğsü", "tereyağı", "krema", "domates püresi", "garam masala", "zencefil", "sarımsak", "yoğurt"],
    "recipe": "1. Yoğurt ve baharatla marine edilen tavukları tavada kızartın.\n2. Sos için tereyağında zencefil, sarımsak ve domates püresini garam masala ile soteleyin.\n3. Kremayı ilave edip pürüzsüz sos elde edin, tavukları ekleyip 10 dakika demlendirin.",
    "macros": "34g Protein, 16g Karbonhidrat, 28g Yağ"
  },
  {
    "id": "recipe_real_7",
    "name": "Chicken Piccata",
    "type": "FOREIGN",
    "theme": ["FIT", "FOREIGN"],
    "cost": 130,
    "totalCost": 130,
    "time": 25,
    "prepTime": 25,
    "calories": 410,
    "heaviness": 4,
    "ingredients": ["tavuk göğsü", "tereyağı", "zeytinyağı", "limon suyu", "kapari", "tavuk suyu", "maydanoz", "un"],
    "recipe": "1. İncelgilmiş tavuk bonfilelerini hafifçe unlayıp zeytinyağında soteleyin.\n2. Tavadan alıp aynı tavaya tavuk suyu, limon suyu, kapari ve tereyağı ekleyip sos koyulaşana kadar çektirin.\n3. Sosu tavukların üzerine döküp taze maydanoz ile servis edin.",
    "macros": "32g Protein, 12g Karbonhidrat, 16g Yağ"
  },
  {
    "id": "recipe_real_8",
    "name": "Kung Pao Chicken",
    "type": "FOREIGN",
    "theme": ["STUDENT", "FOREIGN"],
    "cost": 125,
    "totalCost": 125,
    "time": 20,
    "prepTime": 20,
    "calories": 490,
    "heaviness": 5,
    "ingredients": ["tavuk göğsü", "yer fıstığı", "kuru acı biber", "soya sosu", "susam yağı", "zencefil", "taze soğan", "nişasta"],
    "recipe": "1. Küp doğranmış tavukları nişasta ve soya sosunda marine edin.\n2. Wok tavada susam yağında kuru acı biber, zencefil ve sarımsağı soteleyin.\n3. Tavukları ve kavrulmuş yer fıstıklarını ekleyip yüksek ateşte taze soğanla çevirin.",
    "macros": "30g Protein, 22g Karbonhidrat, 20g Yağ"
  },
  {
    "id": "recipe_real_9",
    "name": "Chicken Kiev",
    "type": "FOREIGN",
    "theme": ["GUEST", "FOREIGN"],
    "cost": 150,
    "totalCost": 150,
    "time": 45,
    "prepTime": 45,
    "calories": 630,
    "heaviness": 8,
    "ingredients": ["tavuk göğsü", "tereyağı", "sarımsak", "maydanoz", "yumurta", "galeta unu", "un", "ayçiçek yağı"],
    "recipe": "1. Sarımsak ve maydanozla yoğrulmuş tereyağını dondurun.\n2. İnceltilmiş tavuk göğsünün ortasına sarımsaklı tereyağını koyup rulo şeklinde sıkıca sarın.\n3. Önce una, sonra çırpılmış yumurtaya ve galeta ununa bulayıp kızgın yağda altın sarısı olana kadar kızartın.",
    "macros": "35g Protein, 24g Karbonhidrat, 34g Yağ"
  },
  {
    "id": "recipe_real_10",
    "name": "Tavuklu Mole Poblano",
    "type": "FOREIGN",
    "theme": ["GUEST", "FOREIGN"],
    "cost": 160,
    "totalCost": 160,
    "time": 55,
    "prepTime": 55,
    "calories": 570,
    "heaviness": 7,
    "ingredients": ["tavuk göğsü", "bitter çikolata", "chili biberi", "susam", "domates", "tarçın", "karanfil", "sarımsak"],
    "recipe": "1. Kurutulmuş chılı biberleri, domates, baharatlar ve bitter çikolatadan Meksika usulü zengin bir sos hazırlayın.\n2. Haşlanmış tavuk parçalarını bu özel bitter çikolatalı ve baharatlı sosta pişirin.\n3. Kavrulmuş susam serpiştirerek servis yapın.",
    "macros": "33g Protein, 28g Karbonhidrat, 24g Yağ"
  },
  {
    "id": "recipe_real_11",
    "name": "Piliç Topkapı",
    "type": "LOCAL",
    "theme": ["GUEST", "TRADITIONAL"],
    "cost": 135,
    "totalCost": 135,
    "time": 50,
    "prepTime": 50,
    "calories": 520,
    "heaviness": 6,
    "ingredients": ["tavuk pirzola", "pirinç", "fıstık", "kuş üzümü", "tereyağı", "yenibahar", "tarçın", "salça"],
    "recipe": "1. İç pilav için çam fıstığı, kuş üzümü ve baharatlarla kokulu pirinç pilavı pişirin.\n2. Derisiz kemiksiz tavuk pirzolaların içine pilavı doldurup sarın ve fırın tepsisine dizin.\n3. Üzerine salçalı sos sürüp fırında nar gibi kızarana kadar pişirin.",
    "macros": "30g Protein, 42g Karbonhidrat, 18g Yağ"
  },
  {
    "id": "recipe_real_12",
    "name": "Piliç Cordon Bleu",
    "type": "FOREIGN",
    "theme": ["GUEST", "FOREIGN"],
    "cost": 145,
    "totalCost": 145,
    "time": 35,
    "prepTime": 35,
    "calories": 590,
    "heaviness": 7,
    "ingredients": ["tavuk göğsü", "dana füme et", "kaşar peyniri", "un", "yumurta", "galeta unu", "tereyağı"],
    "recipe": "1. İnceltilmiş tavuk göğsünün arasına füme et ve kaşar peyniri dilimi yerleştirip katlayın.\n2. Kenarlarını kapatıp un, yumurta ve galeta ununa bulayın.\n3. Tavada veya fırında peyniri eriyene kadar pişirin.",
    "macros": "38g Protein, 20g Karbonhidrat, 26g Yağ"
  },
  {
    "id": "recipe_real_13",
    "name": "Tavuklu Sultan Kebabı",
    "type": "LOCAL",
    "theme": ["GUEST", "TRADITIONAL"],
    "cost": 125,
    "totalCost": 125,
    "time": 45,
    "prepTime": 45,
    "calories": 530,
    "heaviness": 6,
    "ingredients": ["tavuk göğsü", "yufka", "patates", "beşamel sos", "kaşar peyniri", "kuru soğan", "biber salçası"],
    "recipe": "1. Tavuk, küp patates ve soğanla lezzetli bir sote hazırlayın.\n2. Yufka parçalarını kaseye serip tavuklu harçla doldurun, kapatıp tepsiye ters çevirin.\n3. Üzerine beşamel sos ve kaşar rendesi koyup fırında kızartın.",
    "macros": "32g Protein, 36g Karbonhidrat, 22g Yağ"
  },
  {
    "id": "recipe_real_14",
    "name": "Çerkes Tavuğu",
    "type": "LOCAL",
    "theme": ["GUEST", "TRADITIONAL"],
    "cost": 115,
    "totalCost": 115,
    "time": 40,
    "prepTime": 40,
    "calories": 460,
    "heaviness": 5,
    "ingredients": ["tavuk göğsü", "ceviz içi", "bayat ekmek içi", "sarımsak", "tavuk suyu", "ceviz yağı", "toz kırmızı biber"],
    "recipe": "1. Haşlanmış tavuk göğsünü tel tel didikleyin.\n2. Çekilmiş ceviz içi, bayat ekmek içi, sarımsak ve tavuk suyunu macun kıvamına gelene kadar yoğurun.\n3. Didiklenmiş tavukla birleştirip üzerine kızdırılmış ceviz yağı ve pul biber gezdirin.",
    "macros": "34g Protein, 14g Karbonhidrat, 24g Yağ"
  },
  {
    "id": "recipe_real_15",
    "name": "Hünkâr Beğendi",
    "type": "LOCAL",
    "theme": ["GUEST", "RAMADAN", "TRADITIONAL"],
    "cost": 210,
    "totalCost": 210,
    "time": 70,
    "prepTime": 70,
    "calories": 560,
    "heaviness": 7,
    "ingredients": ["kuşbaşı dana", "közlenmiş patlıcan", "süt", "un", "taze kaşar", "tereyağı", "kuru soğan", "domates salçası"],
    "recipe": "1. Köz patlıcanları ince kıyıp tereyağında unla kavurun, süt ve kaşar rendesi ekleyerek nefis beğendi hazırlayın.\n2. Yumuşacık pişen dana kuşbaşı etini domates salçalı sosla soteleyin.\n3. Sıcak beğendi yatağının üzerine etleri yerleştirip servis yapın.",
    "macros": "36g Protein, 18g Karbonhidrat, 28g Yağ"
  },
  {
    "id": "recipe_real_16",
    "name": "Ali Nazik Kebabı",
    "type": "LOCAL",
    "theme": ["GUEST", "TRADITIONAL"],
    "cost": 195,
    "totalCost": 195,
    "time": 45,
    "prepTime": 45,
    "calories": 510,
    "heaviness": 6,
    "ingredients": ["zırh kıyması", "közlenmiş patlıcan", "sarımsaklı yoğurt", "tereyağı", "pul biber", "domates", "biber"],
    "recipe": "1. Közlenmiş patlıcanları sarımsaklı yoğurt ile çırpıp servis tabağına yayın.\n2. Tereyağında kavrulan lezzetli zırh kıymasını patlıcanlı yatağın üzerine dökün.\n3. Kızgın tereyağlı pul biber ve köz biberlerle süsleyin.",
    "macros": "30g Protein, 14g Karbonhidrat, 26g Yağ"
  },
  {
    "id": "recipe_real_17",
    "name": "Çökertme Kebabı",
    "type": "LOCAL",
    "theme": ["GUEST", "TRADITIONAL"],
    "cost": 220,
    "totalCost": 220,
    "time": 50,
    "prepTime": 50,
    "calories": 610,
    "heaviness": 7,
    "ingredients": ["bonfile dana", "kibrit patates", "sarımsaklı yoğurt", "tereyağı", "domates sosu", "kekik"],
    "recipe": "1. Patatesleri kibrit çöpü inceliğinde doğrayıp çıtır çıtır kızartın.\n2. Dana jülyen bonfileleri yüksek ateşte soteleyin.\n3. Tabağa sırasıyla çıtır patates, sarımsaklı yoğurt, etler ve tereyağlı domates sos dökün.",
    "macros": "38g Protein, 34g Karbonhidrat, 30g Yağ"
  },
  {
    "id": "recipe_real_18",
    "name": "Kayseri Mantısı",
    "type": "LOCAL",
    "theme": ["RAMADAN", "TRADITIONAL"],
    "cost": 110,
    "totalCost": 110,
    "time": 90,
    "prepTime": 90,
    "calories": 520,
    "heaviness": 7,
    "ingredients": ["kıyma", "un", "sarımsaklı yoğurt", "tereyağı", "salça", "nane", "sumak"],
    "recipe": "1. Bir kaşığa 40 tane sığacak küçüklükte mantıları büküp tuzlu suda haşlayın.\n2. Sarımsaklı yoğurt ve salçalı kızgın tereyağlı sos gezdirip sumak ve nane serpin.",
    "macros": "22g Protein, 58g Karbonhidrat, 16g Yağ"
  },
  {
    "id": "recipe_real_19",
    "name": "Antep Çıtır Lahmacun",
    "type": "LOCAL",
    "theme": ["FAMILY", "TRADITIONAL"],
    "cost": 85,
    "totalCost": 85,
    "time": 30,
    "prepTime": 30,
    "calories": 440,
    "heaviness": 5,
    "ingredients": ["zırh kıyması", "maydanoz", "sarımsak", "domates", "biber", "biber salçası", "taze nane"],
    "recipe": "1. İncecik açılan taş fırın hamurunun üzerine sarımsaklı zırh kıyma harcını yayın.\n2. Yüksek ısılı fırında kenarları çıtır olana kadar pişirip taze maydanoz ve limonla servis yapın.",
    "macros": "24g Protein, 46g Karbonhidrat, 14g Yağ"
  },
  {
    "id": "recipe_real_20",
    "name": "Fettuccine Alfredo",
    "type": "FOREIGN",
    "theme": ["STUDENT", "FOREIGN"],
    "cost": 140,
    "totalCost": 140,
    "time": 25,
    "prepTime": 25,
    "calories": 620,
    "heaviness": 8,
    "ingredients": ["fettuccine makarna", "tavuk göğsü", "krema", "kültür mantarı", "tereyağı", "parmesan"],
    "recipe": "1. Makarnayı al dente haşlayın.\n2. Mantar ve tavukları tereyağında soteleyin, krema ve parmesan ekleyip makarnayla harmanlayın.",
    "macros": "28g Protein, 55g Karbonhidrat, 28g Yağ"
  }
];
