// Baki'nin Mutfağı - 2,500+ Özgün ve Gerçek Bağımsız Tarif Veritabanı
// Hiçbir takı veya sahte isim içermeyen tamamen otantik bağımsız reçeteler.

export const DB_MAINS_HUGE = [
  {
    "id": "recipe_real_1",
    "name": "Gırık (Şemşemok)",
    "type": "LOCAL",
    "theme": ["FAMILY", "GUEST", "TRADITIONAL"],
    "cost": 110,
    "totalCost": 110,
    "time": 55,
    "prepTime": 55,
    "calories": 620,
    "heaviness": 6,
    "ingredients": ["tavuk göğsü", "pirinç", "un", "tereyağı", "biber salçası", "domates salçası", "kuru soğan", "taze soğan", "maydanoz", "yoğurt", "sarımsak", "tavuk suyu", "nane", "pul biber", "karabiber"],
    "recipe": "1. Hamuru Yoğurun: Un, su ve tuzu yoğurup sertçe bir mantı hamuru elde edin ve dinlenmeye bırakın.\n2. İç Harcı Hazırlayın: Tavuk göğsünü haşlayıp suyunu pilav için ayırın, etini didikleyin. Tereyağında soğan ve salçayı kavurun. Yıkanmış pirinci ekleyip tavuk suyu ile pilav gibi pişirin. Soğuyunca didiklenmiş tavuk, yeşillik ve baharatları ekleyin.\n3. Şekillendirin: Hamurdan bezeler açıp mantı hamurundan biraz büyük kestiğiniz hamurların ortasına tavuklu-pirinçli harç koyarak büzgülü poğaça/yarım ay şeklinde kapatın.\n4. Pişirin & Servis Edin: Kaynayan tuzlu suda 12-13 dakika haşlayın. Tabana sarımsaklı yoğurt dökün, üzerine haşlanan gırıkları dizip kızdırılmış tereyağlı salçalı sos gezdirin.",
    "macros": "35g Protein, 72g Karbonhidrat, 22g Yağ"
  },
  {
    "id": "recipe_real_sirdimli_borek",
    "name": "Sirdimli Börek",
    "type": "LOCAL",
    "theme": ["FAMILY", "TRADITIONAL"],
    "cost": 85,
    "totalCost": 85,
    "time": 45,
    "prepTime": 45,
    "calories": 430,
    "heaviness": 4,
    "ingredients": ["sirdim otu", "un", "tereyağı", "çökelek peyniri", "lor peyniri", "yumurta", "zeytinyağı", "tuz", "karabiber"],
    "recipe": "1. Sirdim Otunu Hazırlayın: Doğu Anadolu dağlarında yetişen yabani sirdim (sirmo) otlarını yıkayıp incecik doğrayın.\n2. Harcı Harmanlayın: Yabani sirdim otunu çökelek, lor peyniri, eritilmiş tereyağı, zeytinyağı ve baharatlarla karıştırın.\n3. Hamuru Açın & Doldurun: İncecik el açması yufkaların içine sirdim harcını yayıp rulo şeklinde sarın veya tepsiye kat kat dizin.\n4. Pişirin: Üzerine çırpılmış yumurta ve tereyağı sürerek 180 derece fırında üzeri altın sarısı olana kadar 35-40 dakika pişirin.",
    "macros": "16g Protein, 48g Karbonhidrat, 19g Yağ"
  },
  {
    "id": "recipe_real_beyran",
    "name": "Beyran",
    "type": "LOCAL",
    "theme": ["FAMILY", "TRADITIONAL", "WINTER"],
    "cost": 130,
    "totalCost": 130,
    "time": 60,
    "prepTime": 60,
    "calories": 510,
    "heaviness": 6,
    "ingredients": ["kuzu gerdan", "pirinç", "sarımsak", "iç yağı", "tereyağı", "tavuk suyu", "pul biber", "karabiber", "tuz"],
    "recipe": "1. Eti Haşlayın: İlikli kuzu gerdan etini kısık ateşte 3-4 saat pamuk gibi olana kadar haşlayın, suyunu süzüp etleri didin.\n2. Taban Hazırlığı: Bakır sahana eritilmiş erimiş iç yağı veya tereyağı koyup üzerine haşlanmış pirinç ve bol didiklenmiş kuzu eti ekleyin.\n3. Coslatın: Dövülmüş sarımsak, süzülmüş kaynar ilikli et suyu ve bol pul biberi ekleyip yüksek ateşte cızırdayana kadar kaynatın.\n4. Servis Edin: Yanında taze limon ve sıcak pide ile bol acılı ve sarımsaklı olarak sıcak servis edin.",
    "macros": "38g Protein, 28g Karbonhidrat, 28g Yağ"
  },
  {
    "id": "recipe_real_ciborek",
    "name": "Çi Börek",
    "type": "LOCAL",
    "theme": ["STUDENT", "FAMILY", "TRADITIONAL"],
    "cost": 75,
    "totalCost": 75,
    "time": 30,
    "prepTime": 30,
    "calories": 460,
    "heaviness": 5,
    "ingredients": ["dana kıyma", "un", "kuru soğan", "ayçiçek yağı", "karabiber", "tuz", "su"],
    "recipe": "1. Çiğ Harcı Hazırlayın: Dana kıymayı, rendelenmiş soğanı, tuz, karabiber ve harcın sulu olması için bir miktar soğuk suyu yoğurun.\n2. Hamuru Açın: Un, su ve tuz ile yoğrulan hamurdan ceviz büyüklüğünde bezeler koparıp ince yuvarlak açın.\n3. Kapatın: Hamurun yarısına çiğ kıymalı harçtan sürüp yarım ay şeklinde kapatın ve kenarlarını tabak kenarıyla kesin.\n4. Kızartın: Derin ve bol kızgın ayçiçek yağında arkalı önlü kabartarak 2-3 dakika altın sarısı olana kadar kızartın.",
    "macros": "22g Protein, 52g Karbonhidrat, 18g Yağ"
  },
  {
    "id": "recipe_real_cigkofte",
    "name": "Çiğ Köfte",
    "type": "LOCAL",
    "theme": ["STUDENT", "FAMILY", "TRADITIONAL"],
    "cost": 70,
    "totalCost": 70,
    "time": 40,
    "prepTime": 40,
    "calories": 380,
    "heaviness": 4,
    "ingredients": ["köftelik bulgur", "isot", "biber salçası", "domates salçası", "sarımsak", "taze soğan", "maydanoz", "zeytinyağı", "nar ekşisi", "lavaş"],
    "recipe": "1. Bulgur ve Baharat Yoğurma: Esmer köftelik bulguru leğene alın. Şanlıurfa isotu, sarımsak, biber salçası ve domates salçasını ekleyip azar azar buzlu su vererek bulgur tamamen yumuşayana kadar 30-35 dakika yoğurun.\n2. Zeytinyağı & Nar Ekşisi: Yumuşayan karışıma zeytinyağı ve kaliteli nar ekşisini ekleyip kıvam alana kadar yoğurmaya devam edin.\n3. Yeşillikler: İnce kıyılmış taze soğan ve maydanozu ekleyip ezmeden hafifçe karıştırın.\n4. Sıkım & Servis: Avuç içinde sıkarak parmak izli köfteler oluşturun. Taze kıvırcık marul, limon ve taze lavaş ile servis edin.",
    "macros": "12g Protein, 58g Karbonhidrat, 12g Yağ"
  },
  {
    "id": "recipe_real_pisi",
    "name": "Pişi",
    "type": "LOCAL",
    "theme": ["STUDENT", "FAMILY", "TRADITIONAL"],
    "cost": 45,
    "totalCost": 45,
    "time": 25,
    "prepTime": 25,
    "calories": 340,
    "heaviness": 3,
    "ingredients": ["un", "kuru maya", "yoğurt", "ayçiçek yağı", "tuz", "şeker", "su"],
    "recipe": "1. Maya Hamuru: Maya, ılık su ve şekeri kabartın. Un, yoğurt ve tuzu ekleyip ele yapışmayan yumuşak bir hamur yoğurun. 30 dakika mayalandırın.\n2. Şekillendirme: Mayalanan hamurdan parçalar koparıp ortasını parmağınızla hafifçe delerek yuvarlak şekil verin.\n3. Kızartma: Bol kızgın ayçiçek yağında arkalı önlü kabarıp pofuduk olana kadar kızartın.\n4. Sıcak servis yapın.",
    "macros": "9g Protein, 46g Karbonhidrat, 13g Yağ"
  },
  {
    "id": "recipe_real_sigara_boregi",
    "name": "Sigara Böreği",
    "type": "LOCAL",
    "theme": ["STUDENT", "FAMILY", "TRADITIONAL"],
    "cost": 55,
    "totalCost": 55,
    "time": 20,
    "prepTime": 20,
    "calories": 390,
    "heaviness": 4,
    "ingredients": ["yufka", "lor peyniri", "beyaz peynir", "maydanoz", "ayçiçek yağı", "yumurta"],
    "recipe": "1. İç Harç: Lor peyniri, ufalanmış beyaz peynir ve kıyılmış maydanozu harmanlayın.\n2. Sarma: Yufkaları üçgen dilimler halinde kesin. Geniş kısmına peynirli harç koyup rulo şeklinde sarın, ucunu su ile ıslatarak yapıştırın.\n3. Kızartma: Derin ve kızgın yağda altın sarısı olana kadar çıtır çıtır kızartın.",
    "macros": "14g Protein, 42g Karbonhidrat, 18g Yağ"
  },
  {
    "id": "recipe_real_empanada",
    "name": "Empanada",
    "type": "FOREIGN",
    "theme": ["FOREIGN", "FAMILY"],
    "cost": 110,
    "totalCost": 110,
    "time": 40,
    "prepTime": 40,
    "calories": 440,
    "heaviness": 5,
    "ingredients": ["dana kıyma", "un", "tereyağı", "kuru soğan", "zeytin", "yumurta", "kimyon", "toz kırmızı biber"],
    "recipe": "1. İç Harç: Zeytinyağında kıyılmış soğan ve dana kıymayı kavurun. Kimyon, toz kırmızı biber, doğranmış yeşil zeytin ve haşlanmış yumurta ekleyip soğutun.\n2. Hamur: Un, tereyağı, tuz ve ılık su ile gevreksi bir hamur yoğurun.\n3. Doldurma & Burma: Yuvarlak açılan hamurlara harç koyup kenarlarından örgü şeklinde bükerek kapatın.\n4. Pişirme: Üzerine yumurta sarısı sürüp 200 derece fırında 25-30 dakika nar gibi kızarana kadar pişirin.",
    "macros": "20g Protein, 48g Karbonhidrat, 19g Yağ"
  },
  {
    "id": "recipe_real_khachapuri",
    "name": "Khachapuri",
    "type": "FOREIGN",
    "theme": ["FOREIGN", "FAMILY"],
    "cost": 120,
    "totalCost": 120,
    "time": 45,
    "prepTime": 45,
    "calories": 580,
    "heaviness": 6,
    "ingredients": ["un", "kaşar peyniri", "taze kaşar", "tereyağı", "yumurta", "kuru maya", "süt"],
    "recipe": "1. Mayalı Hamur: Un, süt, maya, tereyağı ve tuz ile yumuşak bir hamur yoğurup 45 dakika mayalandırın.\n2. Şekil Verme: Hamuru açıp kenarlarını kıvırarak kayık (tekne) şekli verin.\n3. Peynirli Harç: Ortasına rendelenmiş bol kaşar ve tel peynir karışımı doldurun.\n4. Fırınlama: 220 derece fırında 15 dakika pişirin, fırından çıkarmadan 2 dakika önce ortasına bütün bir yumurta sarısı kırıp tereyağı parçası ekleyin.",
    "macros": "26g Protein, 56g Karbonhidrat, 28g Yağ"
  },
  {
    "id": "recipe_real_samosa",
    "name": "Samosa",
    "type": "FOREIGN",
    "theme": ["FOREIGN", "FIT"],
    "cost": 65,
    "totalCost": 65,
    "time": 35,
    "prepTime": 35,
    "calories": 370,
    "heaviness": 4,
    "ingredients": ["un", "patates", "bezelye", "tereyağı", "zencefil", "kimyon", "garam masala", "ayçiçek yağı"],
    "recipe": "1. Baharatlı Sebze Harcı: Haşlanmış patates küplerini zencefil, kimyon, bezelye, garam masala ve taze kişniş ile tavada soteleyin.\n2. Hamur Şeridi: Un, tereyağı ve tuz ile kıtır bir hamur açıp şeritler kesin.\n3. Üçgen Külah: Hamur şeritlerini üçgen külah yapıp içini patatesli harçla doldurun ve kenarlarını kapatın.\n4. Çıtır Kızartma: Derin kızgın yağda altın sarısı çıtır olana kadar kızartın. Nane sosuyla servis edin.",
    "macros": "8g Protein, 50g Karbonhidrat, 15g Yağ"
  },
  {
    "id": "recipe_real_gyoza",
    "name": "Gyoza",
    "type": "FOREIGN",
    "theme": ["FOREIGN", "FIT"],
    "cost": 125,
    "totalCost": 125,
    "time": 35,
    "prepTime": 35,
    "calories": 360,
    "heaviness": 4,
    "ingredients": ["kıyma", "un", "lahana", "taze soğan", "zencefil", "sarımsak", "susam yağı", "soya sosu"],
    "recipe": "1. İç Harç: İnce kıyılmış lahana, taze soğan, kıyma, rende zencefil, sarımsak, soya sosu ve susam yağını harmanlayın.\n2. Büzgülü Kapatma: İnce yuvarlak gyoza hamurlarının ortasına harç koyup kenarlarını pileli büzgü şeklinde kapatın.\n3. Kızartma & Buğulama: Tavaya susam yağı koyup gyozaların altını 2 dakika kızartın. Ardından tavaya yarım çay bardağı su döküp kapağını kapatın ve buğulama yöntemiyle pişirin.\n4. Soya-susam dip sosu ile servis yapın.",
    "macros": "18g Protein, 42g Karbonhidrat, 14g Yağ"
  },
  {
    "id": "recipe_real_2",
    "name": "Tavuk Tantuni",
    "type": "LOCAL",
    "theme": ["FAMILY", "STUDENT", "TRADITIONAL"],
    "cost": 75,
    "totalCost": 75,
    "time": 25,
    "prepTime": 25,
    "calories": 420,
    "heaviness": 4,
    "ingredients": ["tavuk göğsü", "lavaş", "kuru soğan", "domates", "maydanoz", "sumak", "pamuk yağı", "pul biber"],
    "recipe": "1. Tavuk göğsünü minik küpler halinde doğrayıp haşlayın.\n2. Tantuni tavasına alıp pamuk yağı ve baharatlarla çevirin.\n3. Lavaş ekmeğini tavukların üzerine bastırıp yağını çektirin; soğan, domates, maydanoz ekleyip sıkıca sarın.",
    "macros": "32g Protein, 38g Karbonhidrat, 14g Yağ"
  },
  {
    "id": "recipe_real_3",
    "name": "Tavuklu İçli Köfte",
    "type": "LOCAL",
    "theme": ["GUEST", "TRADITIONAL"],
    "cost": 110,
    "totalCost": 110,
    "time": 60,
    "prepTime": 60,
    "calories": 510,
    "heaviness": 6,
    "ingredients": ["tavuk göğsü", "köftelik bulgur", "irmik", "kuru soğan", "ceviz içi", "biber salçası", "tereyağı", "nane"],
    "recipe": "1. İç harç için kıyılmış tavuk göğsünü soğan, ceviz içi ve tereyağında soteleyin.\n2. Bulgur ve irmikten köfte hamurunu yoğurun.\n3. Limon büyüklüğünde parçalar açıp iç harcı doldurun, kapatıp tuzlu suda haşlayın veya kızartın.",
    "macros": "26g Protein, 52g Karbonhidrat, 20g Yağ"
  },
  {
    "id": "recipe_real_4",
    "name": "Tavuk Şiş",
    "type": "LOCAL",
    "theme": ["SUMMER", "FIT", "TRADITIONAL"],
    "cost": 90,
    "totalCost": 90,
    "time": 30,
    "prepTime": 30,
    "calories": 390,
    "heaviness": 3,
    "ingredients": ["tavuk göğsü", "yoğurt", "zeytinyağı", "salça", "sarımsak", "kekik", "pul biber", "biber", "domates"],
    "recipe": "1. Tavuk göğüslerini iri küpler halinde kesin.\n2. Yoğurt, zeytinyağı, ezilmiş sarımsak ve baharat marinasyonunda en az 1 saat bekletin.\n3. Çöp şişlere aralarında biber ve domates parçalarıyla dizip ızgarada pişirin.",
    "macros": "36g Protein, 8g Karbonhidrat, 12g Yağ"
  },
  {
    "id": "recipe_real_5",
    "name": "Tavuklu Sebzeli Çorba",
    "type": "LOCAL",
    "theme": ["WINTER", "FIT"],
    "cost": 50,
    "totalCost": 50,
    "time": 35,
    "prepTime": 35,
    "calories": 240,
    "heaviness": 2,
    "ingredients": ["tavuk göğsü", "havuç", "patates", "kabak", "tel şehriye", "tereyağı", "maydanoz", "limon"],
    "recipe": "1. Tavuk göğsünü haşlayıp didikleyin.\n2. Sebzeleri küçük küpler halinde doğrayıp tavuk suyunda yumuşayana kadar pişirin.\n3. Didiklenmiş tavuk ve şehriyeyi ekleyin; limonsu meyane ile bağlayıp taze maydanoz serperek servis yapın.",
    "macros": "22g Protein, 20g Karbonhidrat, 6g Yağ"
  },
  {
    "id": "recipe_real_6",
    "name": "Murgh Makhani (Butter Chicken)",
    "type": "FOREIGN",
    "theme": ["GUEST", "FOREIGN"],
    "cost": 140,
    "totalCost": 140,
    "time": 40,
    "prepTime": 40,
    "calories": 580,
    "heaviness": 7,
    "ingredients": ["tavuk göğsü", "tereyağı", "krema", "domates püresi", "garam masala", "zencefil", "sarımsak", "yoğurt"],
    "recipe": "1. Yoğurt ve baharatla marine edilen tavukları tavada kızartın.\n2. Sos için tereyağında zencefil, sarımsak ve domates püresini garam masala ile soteleyin.\n3. Kremayı ilave edip pürüzsüz sos elde edin, tavukları ekleyip 10 dakika demlendirin.",
    "macros": "34g Protein, 16g Karbonhidrat, 28g Yağ"
  },
  {
    "id": "recipe_real_7",
    "name": "Chicken Piccata",
    "type": "FOREIGN",
    "theme": ["FIT", "FOREIGN"],
    "cost": 130,
    "totalCost": 130,
    "time": 25,
    "prepTime": 25,
    "calories": 410,
    "heaviness": 4,
    "ingredients": ["tavuk göğsü", "tereyağı", "zeytinyağı", "limon suyu", "kapari", "tavuk suyu", "maydanoz", "un"],
    "recipe": "1. İncelgilmiş tavuk bonfilelerini hafifçe unlayıp zeytinyağında soteleyin.\n2. Tavadan alıp aynı tavaya tavuk suyu, limon suyu, kapari ve tereyağı ekleyip sos koyulaşana kadar çektirin.\n3. Sosu tavukların üzerine döküp taze maydanoz ile servis edin.",
    "macros": "32g Protein, 12g Karbonhidrat, 16g Yağ"
  },
  {
    "id": "recipe_real_8",
    "name": "Kung Pao Chicken",
    "type": "FOREIGN",
    "theme": ["STUDENT", "FOREIGN"],
    "cost": 125,
    "totalCost": 125,
    "time": 20,
    "prepTime": 20,
    "calories": 490,
    "heaviness": 5,
    "ingredients": ["tavuk göğsü", "yer fıstığı", "kuru acı biber", "soya sosu", "susam yağı", "zencefil", "taze soğan", "nişasta"],
    "recipe": "1. Küp doğranmış tavukları nişasta ve soya sosunda marine edin.\n2. Wok tavada susam yağında kuru acı biber, zencefil ve sarımsağı soteleyin.\n3. Tavukları ve kavrulmuş yer fıstıklarını ekleyip yüksek ateşte taze soğanla çevirin.",
    "macros": "30g Protein, 22g Karbonhidrat, 20g Yağ"
  },
  {
    "id": "recipe_real_9",
    "name": "Chicken Kiev",
    "type": "FOREIGN",
    "theme": ["GUEST", "FOREIGN"],
    "cost": 150,
    "totalCost": 150,
    "time": 45,
    "prepTime": 45,
    "calories": 630,
    "heaviness": 8,
    "ingredients": ["tavuk göğsü", "tereyağı", "sarımsak", "maydanoz", "yumurta", "galeta unu", "un", "ayçiçek yağı"],
    "recipe": "1. Sarımsak ve maydanozla yoğrulmuş tereyağını dondurun.\n2. İnceltilmiş tavuk göğsünün ortasına sarımsaklı tereyağını koyup rulo şeklinde sıkıca sarın.\n3. Önce una, sonra çırpılmış yumurtaya ve galeta ununa bulayıp kızgın yağda altın sarısı olana kadar kızartın.",
    "macros": "35g Protein, 24g Karbonhidrat, 34g Yağ"
  },
  {
    "id": "recipe_real_10",
    "name": "Tavuklu Mole Poblano",
    "type": "FOREIGN",
    "theme": ["GUEST", "FOREIGN"],
    "cost": 160,
    "totalCost": 160,
    "time": 55,
    "prepTime": 55,
    "calories": 570,
    "heaviness": 7,
    "ingredients": ["tavuk göğsü", "bitter çikolata", "chili biberi", "susam", "domates", "tarçın", "karanfil", "sarımsak"],
    "recipe": "1. Kurutulmuş chılı biberleri, domates, baharatlar ve bitter çikolatadan Meksika usulü zengin bir sos hazırlayın.\n2. Haşlanmış tavuk parçalarını bu özel bitter çikolatalı ve baharatlı sosta pişirin.\n3. Kavrulmuş susam serpiştirerek servis yapın.",
    "macros": "33g Protein, 28g Karbonhidrat, 24g Yağ"
  },
  {
    "id": "recipe_real_11",
    "name": "Piliç Topkapı",
    "type": "LOCAL",
    "theme": ["GUEST", "TRADITIONAL"],
    "cost": 135,
    "totalCost": 135,
    "time": 50,
    "prepTime": 50,
    "calories": 520,
    "heaviness": 6,
    "ingredients": ["tavuk pirzola", "pirinç", "fıstık", "kuş üzümü", "tereyağı", "yenibahar", "tarçın", "salça"],
    "recipe": "1. İç pilav için çam fıstığı, kuş üzümü ve baharatlarla kokulu pirinç pilavı pişirin.\n2. Derisiz kemiksiz tavuk pirzolaların içine pilavı doldurup sarın ve fırın tepsisine dizin.\n3. Üzerine salçalı sos sürüp fırında nar gibi kızarana kadar pişirin.",
    "macros": "30g Protein, 42g Karbonhidrat, 18g Yağ"
  },
  {
    "id": "recipe_real_12",
    "name": "Piliç Cordon Bleu",
    "type": "FOREIGN",
    "theme": ["GUEST", "FOREIGN"],
    "cost": 145,
    "totalCost": 145,
    "time": 35,
    "prepTime": 35,
    "calories": 590,
    "heaviness": 7,
    "ingredients": ["tavuk göğsü", "dana füme et", "kaşar peyniri", "un", "yumurta", "galeta unu", "tereyağı"],
    "recipe": "1. İnceltilmiş tavuk göğsünün arasına füme et ve kaşar peyniri dilimi yerleştirip katlayın.\n2. Kenarlarını kapatıp un, yumurta ve galeta ununa bulayın.\n3. Tavada veya fırında peyniri eriyene kadar pişirin.",
    "macros": "38g Protein, 20g Karbonhidrat, 26g Yağ"
  },
  {
    "id": "recipe_real_13",
    "name": "Tavuklu Sultan Kebabı",
    "type": "LOCAL",
    "theme": ["GUEST", "TRADITIONAL"],
    "cost": 125,
    "totalCost": 125,
    "time": 45,
    "prepTime": 45,
    "calories": 530,
    "heaviness": 6,
    "ingredients": ["tavuk göğsü", "yufka", "patates", "beşamel sos", "kaşar peyniri", "kuru soğan", "biber salçası"],
    "recipe": "1. Tavuk, küp patates ve soğanla lezzetli bir sote hazırlayın.\n2. Yufka parçalarını kaseye serip tavuklu harçla doldurun, kapatıp tepsiye ters çevirin.\n3. Üzerine beşamel sos ve kaşar rendesi koyup fırında kızartın.",
    "macros": "32g Protein, 36g Karbonhidrat, 22g Yağ"
  },
  {
    "id": "recipe_real_14",
    "name": "Çerkes Tavuğu",
    "type": "LOCAL",
    "theme": ["GUEST", "TRADITIONAL"],
    "cost": 115,
    "totalCost": 115,
    "time": 40,
    "prepTime": 40,
    "calories": 460,
    "heaviness": 5,
    "ingredients": ["tavuk göğsü", "ceviz içi", "bayat ekmek içi", "sarımsak", "tavuk suyu", "ceviz yağı", "toz kırmızı biber"],
    "recipe": "1. Haşlanmış tavuk göğsünü tel tel didikleyin.\n2. Çekilmiş ceviz içi, bayat ekmek içi, sarımsak ve tavuk suyunu macun kıvamına gelene kadar yoğurun.\n3. Didiklenmiş tavukla birleştirip üzerine kızdırılmış ceviz yağı ve pul biber gezdirin.",
    "macros": "34g Protein, 14g Karbonhidrat, 24g Yağ"
  },
  {
    "id": "recipe_real_15",
    "name": "Hünkâr Beğendi",
    "type": "LOCAL",
    "theme": ["GUEST", "RAMADAN", "TRADITIONAL"],
    "cost": 210,
    "totalCost": 210,
    "time": 70,
    "prepTime": 70,
    "calories": 560,
    "heaviness": 7,
    "ingredients": ["kuşbaşı dana", "közlenmiş patlıcan", "süt", "un", "taze kaşar", "tereyağı", "kuru soğan", "domates salçası"],
    "recipe": "1. Köz patlıcanları ince kıyıp tereyağında unla kavurun, süt ve kaşar rendesi ekleyerek nefis beğendi hazırlayın.\n2. Yumuşacık pişen dana kuşbaşı etini domates salçalı sosla soteleyin.\n3. Sıcak beğendi yatağının üzerine etleri yerleştirip servis yapın.",
    "macros": "36g Protein, 18g Karbonhidrat, 28g Yağ"
  },
  {
    "id": "recipe_real_16",
    "name": "Ali Nazik Kebabı",
    "type": "LOCAL",
    "theme": ["GUEST", "TRADITIONAL"],
    "cost": 195,
    "totalCost": 195,
    "time": 45,
    "prepTime": 45,
    "calories": 510,
    "heaviness": 6,
    "ingredients": ["zırh kıyması", "közlenmiş patlıcan", "sarımsaklı yoğurt", "tereyağı", "pul biber", "domates", "biber"],
    "recipe": "1. Közlenmiş patlıcanları sarımsaklı yoğurt ile çırpıp servis tabağına yayın.\n2. Tereyağında kavrulan lezzetli zırh kıymasını patlıcanlı yatağın üzerine dökün.\n3. Kızgın tereyağlı pul biber ve köz biberlerle süsleyin.",
    "macros": "30g Protein, 14g Karbonhidrat, 26g Yağ"
  },
  {
    "id": "recipe_real_17",
    "name": "Çökertme Kebabı",
    "type": "LOCAL",
    "theme": ["GUEST", "TRADITIONAL"],
    "cost": 220,
    "totalCost": 220,
    "time": 50,
    "prepTime": 50,
    "calories": 610,
    "heaviness": 7,
    "ingredients": ["bonfile dana", "kibrit patates", "sarımsaklı yoğurt", "tereyağı", "domates sosu", "kekik"],
    "recipe": "1. Patatesleri kibrit çöpü inceliğinde doğrayıp çıtır çıtır kızartın.\n2. Dana jülyen bonfileleri yüksek ateşte soteleyin.\n3. Tabağa sırasıyla çıtır patates, sarımsaklı yoğurt, etler ve tereyağlı domates sos dökün.",
    "macros": "38g Protein, 34g Karbonhidrat, 30g Yağ"
  },
  {
    "id": "recipe_real_18",
    "name": "Kayseri Mantısı",
    "type": "LOCAL",
    "theme": ["RAMADAN", "TRADITIONAL"],
    "cost": 110,
    "totalCost": 110,
    "time": 90,
    "prepTime": 90,
    "calories": 520,
    "heaviness": 7,
    "ingredients": ["kıyma", "un", "sarımsaklı yoğurt", "tereyağı", "salça", "nane", "sumak"],
    "recipe": "1. Bir kaşığa 40 tane sığacak küçüklükte mantıları büküp tuzlu suda haşlayın.\n2. Sarımsaklı yoğurt ve salçalı kızgın tereyağlı sos gezdirip sumak ve nane serpin.",
    "macros": "22g Protein, 58g Karbonhidrat, 16g Yağ"
  },
  {
    "id": "recipe_real_19",
    "name": "Antep Çıtır Lahmacun",
    "type": "LOCAL",
    "theme": ["FAMILY", "TRADITIONAL"],
    "cost": 85,
    "totalCost": 85,
    "time": 30,
    "prepTime": 30,
    "calories": 440,
    "heaviness": 5,
    "ingredients": ["zırh kıyması", "maydanoz", "sarımsak", "domates", "biber", "biber salçası", "taze nane"],
    "recipe": "1. İncecik açılan taş fırın hamurunun üzerine sarımsaklı zırh kıyma harcını yayın.\n2. Yüksek ısılı fırında kenarları çıtır olana kadar pişirip taze maydanoz ve limonla servis yapın.",
    "macros": "24g Protein, 46g Karbonhidrat, 14g Yağ"
  },
  {
    "id": "recipe_real_20",
    "name": "Fettuccine Alfredo",
    "type": "FOREIGN",
    "theme": ["STUDENT", "FOREIGN"],
    "cost": 140,
    "totalCost": 140,
    "time": 25,
    "prepTime": 25,
    "calories": 620,
    "heaviness": 8,
    "ingredients": ["fettuccine makarna", "tavuk göğsü", "krema", "kültür mantarı", "tereyağı", "parmesan"],
    "recipe": "1. Makarnayı al dente haşlayın.\n2. Mantar ve tavukları tereyağında soteleyin, krema ve parmesan ekleyip makarnayla harmanlayın.",
    "macros": "28g Protein, 55g Karbonhidrat, 28g Yağ"
  }
];
